# Generated by Django 2.1 on 2018-08-23 11:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180820_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='additional_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
